app/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.forms import ContactForm
from loguru import logger

main_bp = Blueprint("main_bp", __name__)


# Налаштовуємо логування
logger.add("logs/contact.log", format="{time} {level} {message}", level="INFO", rotation="1 MB")

@main_bp.route("/")
def main():
    return render_template("base.html")

@main_bp.route("/resume")
def resume():
    return render_template("resume.html")

@main_bp.route("/base")
def base():
    return render_template("base.html")

@main_bp.route("/contact", methods=["GET", "POST"])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        logger.info(
            f"New message from {form.name.data} ({form.email.data}, {form.phone.data}) | Subject: {form.subject.data} | Message: {form.message.data}"
        )
        flash(f"Дякуємо, {form.name.data}! Повідомлення успішно надіслано.", "success")
        return redirect(url_for("main_bp.contact"))
    elif form.is_submitted() and not form.validate():
        flash("Будь ласка, виправте помилки у формі.", "danger")
    return render_template("contacts.html", form=form)

app/templates/includes/footer.html
<footer class="text-center py-3 bg-dark text-white mt-5">
    <p>&copy; Богдан Павлюк. ІПЗ-32</p>
</footer>

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('main_bp.resume') }}">Моє резюме</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main_bp.resume') }}">Моє резюме</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('main_bp.contact') }}">Контакти</a></li>
      </ul>
    </div>
  </div>
</nav>